-- RedefineTables
CREATE TABLE "new_technical_specs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicle_year_id" INTEGER NOT NULL,
    "source_url" TEXT NOT NULL,
    "scraped_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "raw_data" TEXT,
    "year" TEXT,
    "fuel" TEXT,
    "configuration" TEXT,
    "warranty" TEXT,
    "generation" TEXT,
    "seats" TEXT,
    "platform" TEXT,
    "doors" TEXT,
    "size" TEXT,
    "origin" TEXT,
    "propulsion" TEXT,
    "series" TEXT,
    "acceleration_0_100" TEXT,
    "top_speed_g" TEXT,
    "top_speed_e" TEXT,
    "weight_power_ratio" TEXT,
    "weight_torque_ratio" TEXT,
    "specific_power" TEXT,
    "specific_torque" TEXT,
    "engine_code" TEXT,
    "unit_displacement" TEXT,
    "displacement" TEXT,
    "bore" TEXT,
    "stroke" TEXT,
    "cylinders" TEXT,
    "cylinders_arrangement" TEXT,
    "valves_per_cylinder" TEXT,
    "valve_control" TEXT,
    "valve_variation" TEXT,
    "tappets" TEXT,
    "aspiration" TEXT,
    "feeding" TEXT,
    "installation" TEXT,
    "arrangement" TEXT,
    "compression_ratio" TEXT,
    "drive_actuation" TEXT,
    "power_hp_g" TEXT,
    "power_hp_e" TEXT,
    "max_power_rpm" TEXT,
    "torque_g" TEXT,
    "torque_e" TEXT,
    "max_torque_rpm" TEXT,
    "coupling" TEXT,
    "gearbox" TEXT,
    "gearbox_code" TEXT,
    "gears" TEXT,
    "traction" TEXT,
    "height" TEXT,
    "width" TEXT,
    "length" TEXT,
    "wheelbase" TEXT,
    "front_track" TEXT,
    "rear_track" TEXT,
    "weight" TEXT,
    "payload" TEXT,
    "trunk_capacity" TEXT,
    "fuel_tank" TEXT,
    "front_brakes" TEXT,
    "rear_brakes" TEXT,
    "sidewall_height" TEXT,
    "frontal_area" TEXT,
    "corrected_frontal_area" TEXT,
    "drag_coefficient" TEXT,
    "steering_assist" TEXT,
    "turning_diameter" TEXT,
    "front_suspension" TEXT,
    "rear_suspension" TEXT,
    "elastic_element" TEXT,
    "city_consumption_g" TEXT,
    "highway_consumption_g" TEXT,
    "city_range_g" TEXT,
    "highway_range_g" TEXT,
    "city_consumption_e" TEXT,
    "highway_consumption_e" TEXT,
    "city_range_e" TEXT,
    "highway_range_e" TEXT,
    CONSTRAINT "technical_specs_vehicle_year_id_fkey" FOREIGN KEY ("vehicle_year_id") REFERENCES "vehicle_years" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Copy existing data (only columns that exist in old table)
INSERT INTO "new_technical_specs" (
    "id", "vehicle_year_id", "source_url", "scraped_at", "raw_data",
    "engine_code", "power_hp_g", "torque_g", "gearbox", "fuel",
    "city_consumption_g", "highway_consumption_g"
)
SELECT
    "id", "vehicle_year_id", "source_url", "scraped_at", "raw_data",
    "engine", "power_hp", "torque", "transmission", "fuel_type",
    "consumption_city", "consumption_highway"
FROM "technical_specs";

-- Swap tables
DROP TABLE "technical_specs";
ALTER TABLE "new_technical_specs" RENAME TO "technical_specs";

-- Recreate unique index
CREATE UNIQUE INDEX "technical_specs_vehicle_year_id_key" ON "technical_specs"("vehicle_year_id");
